# Generated by Django 5.2.13 on 2026-04-11 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email Address')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('rm_orders_count', models.IntegerField(default=0, verbose_name='RM Orders Count')),
                ('ms_orders_count', models.IntegerField(default=0, verbose_name='MS Orders Count')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Value (₹)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'ordering': ['-created_at'],
            },
        ),
    ]
