# Generated by Django 5.2.13 on 2026-04-11 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RMOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Order ID')),
                ('category', models.CharField(choices=[('School', 'School'), ('Corporate', 'Corporate'), ('Hospital', 'Hospital'), ('Security', 'Security'), ('Business & Corporate', 'Business & Corporate'), ('institutional', 'Institutional'), ('House keeping', 'House Keeping'), ('Medical', 'Medical'), ('Industrial', 'Industrial'), ('Multi Purpose', 'Multi Purpose')], default='School', max_length=50, verbose_name='Category')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='Order Date')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Delivery Date')),
                ('ordered_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Order By')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount (₹)')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('status', models.CharField(choices=[('pending', '⏳ Pending'), ('approved', '👍 Approved'), ('ready', '🎯 Ready'), ('shipped', '🚚 Shipped'), ('delivered', '📦 Delivered')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rm_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rm_orders', to='uniform_app.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'RM Order',
                'verbose_name_plural': 'RM Orders',
                'db_table': 'rm_orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
