# Generated by Django 5.2.13 on 2026-04-11 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0004_rmorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Order ID')),
                ('gender', models.CharField(choices=[('Ladies', '👩 Ladies'), ('Gents', '👨 Gents')], default='Gents', max_length=10, verbose_name='Gender')),
                ('category', models.CharField(choices=[('School', 'School'), ('Corporate', 'Corporate'), ('Hospital', 'Hospital'), ('Security', 'Security'), ('Business & Corporate', 'Business & Corporate'), ('institutional', 'Institutional'), ('House keeping', 'House Keeping'), ('Medical', 'Medical'), ('Industrial', 'Industrial'), ('Multi Purpose', 'Multi Purpose')], default='School', max_length=50, verbose_name='Category')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='Order Date')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Delivery Date')),
                ('ordered_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Order By')),
                ('tailor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tailor Name')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount (₹)')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('status', models.CharField(choices=[('pending', '⏳ Pending'), ('approved', '👍 Approved'), ('In Cutting', '✂️ In Cutting'), ('In Stitching', '🪡 In Stitching'), ('qc', '✅ Quality Check'), ('ready', '🎯 Ready'), ('shipped', '🚚 Shipped'), ('delivered', '📦 Delivered')], default='pending', max_length=20, verbose_name='Status')),
                ('chest', models.FloatField(blank=True, null=True, verbose_name='Chest (inches)')),
                ('waist', models.FloatField(blank=True, null=True, verbose_name='Waist (inches)')),
                ('hip', models.FloatField(blank=True, null=True, verbose_name='Hip (inches)')),
                ('shoulder', models.FloatField(blank=True, null=True, verbose_name='Shoulder (inches)')),
                ('length', models.FloatField(blank=True, null=True, verbose_name='Length (inches)')),
                ('sleeve_length', models.FloatField(blank=True, null=True, verbose_name='Sleeve Length (inches)')),
                ('armhole', models.FloatField(blank=True, null=True, verbose_name='Armhole (inches)')),
                ('neck', models.FloatField(blank=True, null=True, verbose_name='Neck (inches)')),
                ('collar', models.FloatField(blank=True, null=True, verbose_name='Collar (inches)')),
                ('bicep', models.FloatField(blank=True, null=True, verbose_name='Bicep (inches)')),
                ('elbow', models.FloatField(blank=True, null=True, verbose_name='Elbow (inches)')),
                ('cuff', models.FloatField(blank=True, null=True, verbose_name='Cuff (inches)')),
                ('thigh', models.FloatField(blank=True, null=True, verbose_name='Thigh (inches)')),
                ('knee', models.FloatField(blank=True, null=True, verbose_name='Knee (inches)')),
                ('bottom', models.FloatField(blank=True, null=True, verbose_name='Bottom (inches)')),
                ('rise', models.FloatField(blank=True, null=True, verbose_name='Rise (inches)')),
                ('inseam', models.FloatField(blank=True, null=True, verbose_name='Inseam (inches)')),
                ('bust', models.FloatField(blank=True, null=True, verbose_name='Bust (inches)')),
                ('under_bust', models.FloatField(blank=True, null=True, verbose_name='Under Bust (inches)')),
                ('waist_hip', models.FloatField(blank=True, null=True, verbose_name='Waist to Hip (inches)')),
                ('shoulder_to_waist', models.FloatField(blank=True, null=True, verbose_name='Shoulder to Waist (inches)')),
                ('waist_to_knee', models.FloatField(blank=True, null=True, verbose_name='Waist to Knee (inches)')),
                ('waist_to_floor', models.FloatField(blank=True, null=True, verbose_name='Waist to Floor (inches)')),
                ('arm_length', models.FloatField(blank=True, null=True, verbose_name='Arm Length (inches)')),
                ('wrist', models.FloatField(blank=True, null=True, verbose_name='Wrist (inches)')),
                ('front_neck_depth', models.FloatField(blank=True, null=True, verbose_name='Front Neck Depth (inches)')),
                ('back_neck_depth', models.FloatField(blank=True, null=True, verbose_name='Back Neck Depth (inches)')),
                ('dart_length', models.FloatField(blank=True, null=True, verbose_name='Dart Length (inches)')),
                ('dart_depth', models.FloatField(blank=True, null=True, verbose_name='Dart Depth (inches)')),
                ('special_notes', models.TextField(blank=True, null=True, verbose_name='Special Instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ms_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ms_orders', to='uniform_app.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'MS Order',
                'verbose_name_plural': 'MS Orders',
                'db_table': 'ms_orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
