# Generated by Django 5.2.13 on 2026-04-12 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0005_msorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('Shirt', 'Shirt'), ('Pant', 'Pant'), ('Kurta', 'Kurta'), ('Saree', 'Saree'), ('Blouse', 'Blouse'), ('Lehenga', 'Lehenga'), ('Jacket', 'Jacket'), ('Coat', 'Coat'), ('Trouser', 'Trouser'), ('Other', 'Other')], default='Shirt', max_length=50)),
                ('gender', models.CharField(choices=[('Ladies', '👩 Ladies'), ('Gents', '👨 Gents')], default='Gents', max_length=10)),
                ('quantity', models.IntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('chest', models.FloatField(blank=True, null=True)),
                ('waist', models.FloatField(blank=True, null=True)),
                ('hip', models.FloatField(blank=True, null=True)),
                ('shoulder', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('sleeve_length', models.FloatField(blank=True, null=True)),
                ('armhole', models.FloatField(blank=True, null=True)),
                ('neck', models.FloatField(blank=True, null=True)),
                ('collar', models.FloatField(blank=True, null=True)),
                ('bicep', models.FloatField(blank=True, null=True)),
                ('elbow', models.FloatField(blank=True, null=True)),
                ('cuff', models.FloatField(blank=True, null=True)),
                ('thigh', models.FloatField(blank=True, null=True)),
                ('knee', models.FloatField(blank=True, null=True)),
                ('bottom', models.FloatField(blank=True, null=True)),
                ('rise', models.FloatField(blank=True, null=True)),
                ('inseam', models.FloatField(blank=True, null=True)),
                ('bust', models.FloatField(blank=True, null=True)),
                ('under_bust', models.FloatField(blank=True, null=True)),
                ('waist_hip', models.FloatField(blank=True, null=True)),
                ('shoulder_to_waist', models.FloatField(blank=True, null=True)),
                ('waist_to_knee', models.FloatField(blank=True, null=True)),
                ('waist_to_floor', models.FloatField(blank=True, null=True)),
                ('arm_length', models.FloatField(blank=True, null=True)),
                ('wrist', models.FloatField(blank=True, null=True)),
                ('front_neck_depth', models.FloatField(blank=True, null=True)),
                ('back_neck_depth', models.FloatField(blank=True, null=True)),
                ('dart_length', models.FloatField(blank=True, null=True)),
                ('dart_depth', models.FloatField(blank=True, null=True)),
                ('special_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uniform_app.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='uniform_app.msorder')),
            ],
            options={
                'db_table': 'ms_order_items',
                'ordering': ['-created_at'],
            },
        ),
    ]
