# Generated by Django 5.2.13 on 2026-04-13 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0006_msorderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='RMOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(default='Uniform', max_length=100, verbose_name='Product Type')),
                ('uniform_item', models.CharField(default='Shirt', max_length=100, verbose_name='Uniform Item')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color')),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'XX Large'), ('XXXL', 'XXX Large'), ('Custom', 'Custom Size')], default='M', max_length=20, verbose_name='Size')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount (₹)')),
                ('stock_available', models.BooleanField(default=True, verbose_name='Stock Available')),
                ('stock_check_note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stock Check Note')),
                ('special_notes', models.TextField(blank=True, null=True, verbose_name='Special Instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uniform_app.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='uniform_app.rmorder')),
            ],
            options={
                'db_table': 'rm_order_items',
                'ordering': ['-created_at'],
            },
        ),
    ]
