# Generated by Django 5.2.13 on 2026-04-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0007_rmorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmorderitem',
            name='amount_per_piece',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount per Piece (₹)'),
        ),
        migrations.AlterField(
            model_name='rmorderitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Amount (₹)'),
        ),
    ]
