# Generated by Django 5.2.13 on 2026-04-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0008_rmorderitem_amount_per_piece_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msorderitem',
            name='product_type',
        ),
        migrations.AddField(
            model_name='msorderitem',
            name='person_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Person Name'),
        ),
    ]
