# Generated by Django 5.2.13 on 2026-04-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0009_remove_msorderitem_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmorderitem',
            name='gender',
            field=models.CharField(choices=[('Gents', '👨 Gents'), ('Ladies', '👩 Ladies'), ('Kids', '🧒 Kids')], default='Gents', max_length=10, verbose_name='Gender'),
        ),
    ]
