# Generated by Django 5.2.13 on 2026-04-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0010_rmorderitem_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmorderitem',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='rm_items/', verbose_name='Reference Image'),
        ),
    ]
