# Generated by Django 5.2.13 on 2026-04-17 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0011_rmorderitem_reference_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_no', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Quotation Number')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Quotation Date')),
                ('valid_till', models.DateField(blank=True, null=True, verbose_name='Valid Till')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('customer_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('customer_address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('subject', models.CharField(default='Quotation for Uniform Supply', max_length=500, verbose_name='Subject')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message/Body')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal (₹)')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Discount %')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Discount Amount (₹)')),
                ('gst_percent', models.DecimalField(decimal_places=2, default=18, max_digits=5, verbose_name='GST %')),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='GST Amount (₹)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Amount (₹)')),
                ('status', models.CharField(choices=[('Draft', '📄 Draft'), ('Sent', '📨 Sent'), ('Approved', '✅ Approved'), ('Rejected', '❌ Rejected'), ('Converted', '🔄 Converted')], default='Draft', max_length=20, verbose_name='Status')),
                ('payment_terms', models.TextField(default='50% advance, 50% before dispatch', verbose_name='Payment Terms')),
                ('delivery_time', models.CharField(default='15-20 working days', max_length=255, verbose_name='Delivery Time')),
                ('warranty', models.CharField(default='6 months against manufacturing defects', max_length=255, verbose_name='Warranty')),
                ('validity', models.CharField(default='30 days', max_length=100, verbose_name='Validity')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotations', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='uniform_app.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Quotation',
                'verbose_name_plural': 'Quotations',
                'db_table': 'quotations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('gender', models.CharField(choices=[('Gents', '👨 Gents'), ('Ladies', '👩 Ladies'), ('Kids', '🧒 Kids')], default='Gents', max_length=10, verbose_name='Gender')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('Custom', 'Custom')], default='M', max_length=20, verbose_name='Size')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Unit Price (₹)')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Discount %')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount (₹)')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Item Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='uniform_app.quotation')),
            ],
            options={
                'db_table': 'quotation_items',
                'ordering': ['id'],
            },
        ),
    ]
