# Generated by Django 5.2.13 on 2026-04-18 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0013_vendorcategory_purchaseorder_purchaseorderitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'db_table': 'product_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(editable=False, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Gents', '👨 Gents'), ('Ladies', '👩 Ladies'), ('Kids', '🧒 Kids'), ('Unisex', '👥 Unisex')], default='Unisex', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('additional_images', models.JSONField(blank=True, default=list)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_in_stock', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='uniform_app.productcategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('Custom', 'Custom')], default='M', max_length=10)),
                ('color', models.CharField(choices=[('White', '⚪ White'), ('Black', '⚫ Black'), ('Blue', '🔵 Blue'), ('Red', '🔴 Red'), ('Green', '🟢 Green'), ('Yellow', '🟡 Yellow'), ('Maroon', '🔴 Maroon'), ('Grey', '⬜ Grey'), ('Navy', '🔵 Navy'), ('Other', '🎨 Other')], default='White', max_length=20)),
                ('fabric', models.CharField(choices=[('Cotton', 'Cotton'), ('Polyester', 'Polyester'), ('Linen', 'Linen'), ('Silk', 'Silk'), ('Wool', 'Wool'), ('Velvet', 'Velvet'), ('Denim', 'Denim'), ('Other', 'Other')], default='Cotton', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=10)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='uniform_app.product')),
            ],
            options={
                'db_table': 'product_variants',
                'unique_together': {('product', 'size', 'color', 'fabric')},
            },
        ),
        migrations.CreateModel(
            name='SchoolProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_prices', to='uniform_app.product')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='uniform_app.customer')),
            ],
            options={
                'db_table': 'school_product_prices',
                'unique_together': {('product', 'school')},
            },
        ),
    ]
