# Generated by Django 5.2.13 on 2026-04-18 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0014_productcategory_product_productvariant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(editable=False, max_length=50, unique=True)),
                ('designation', models.CharField(choices=[('cutter', '✂️ Cutter'), ('stitcher', '🪡 Stitcher'), ('finisher', '✨ Finisher'), ('packer', '📦 Packer'), ('supervisor', '👔 Supervisor'), ('tailor', '👕 Tailor')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('total_tasks', models.IntegerField(default=0)),
                ('completed_tasks', models.IntegerField(default=0)),
                ('pending_tasks', models.IntegerField(default=0)),
                ('in_progress_tasks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('task_type', models.CharField(choices=[('cutting', '✂️ Cutting'), ('stitching', '🪡 Stitching'), ('finishing', '✨ Finishing'), ('packing', '📦 Packing'), ('qc', '✅ Quality Check')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_quantity', models.IntegerField(default=1)),
                ('completed_quantity', models.IntegerField(default=0)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', '⏳ Pending'), ('in_progress', '🔄 In Progress'), ('completed', '✅ Completed'), ('rejected', '❌ Rejected')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', '🟢 Low'), ('medium', '🟡 Medium'), ('high', '🔴 High'), ('urgent', '⚠️ Urgent')], default='medium', max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='uniform_app.employee')),
                ('ms_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='uniform_app.msorder')),
                ('rm_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='uniform_app.rmorder')),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['-priority', 'due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_quantity', models.IntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='uniform_app.task')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'task_progress_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
